name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login, build and push
        run: |
          # Login
          echo ${{secrets.GITHUB_TOKEN}} | docker login ghcr.io -u windsource --password-stdin
          # Create new builder
          docker buildx create --name mybuilder --driver docker-container --bootstrap
          # Use new builder
          docker buildx use mybuilder
          # Build and push
          TAG=$(date +%Y%m%d%H%M)
          echo "Tag=$TAG"
          docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/windsource/techblog:$TAG --push .
  
