name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Build the Docker image
      run: |
        IMAGE_BASE=ghcr.io/windsource/techblog
        IMAGE_TAG=$(date +%Y%m%d%H%M)
        echo "IMAGE_BASE=$IMAGE_BASE" >> $GITHUB_ENV
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
        docker build . --file Dockerfile --tag $IMAGE_BASE:$IMAGE_TAG

    - name: Push the Docker image
      run: |
        echo ${{ secrets.PAT_GHCR }} | docker login ghcr.io -u windsource --password-stdin
        echo "Tag=$IMAGE_TAG"
        docker push $IMAGE_BASE:$IMAGE_TAG        
    
        

  
